// <auto-generated />
using App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20210524204317_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("App.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<float>("Grades")
                        .HasColumnType("REAL");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Grade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Calculus",
                            Grades = 100f,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Physics",
                            Grades = 90f,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Writing",
                            Grades = 30f,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Speech",
                            Grades = 50f,
                            StudentId = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseName = "Calculus",
                            Grades = 10f,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseName = "Physics",
                            Grades = 20f,
                            StudentId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseName = "Writing",
                            Grades = 30f,
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("App.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Classification")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            Classification = 1,
                            FirstName = "Kevin",
                            LastName = "Huynh"
                        },
                        new
                        {
                            Id = 2,
                            Age = 23,
                            Classification = 2,
                            FirstName = "Dummy",
                            LastName = "Name"
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            Classification = 4,
                            FirstName = "Water",
                            LastName = "CAP"
                        });
                });

            modelBuilder.Entity("App.Models.Grade", b =>
                {
                    b.HasOne("App.Models.Student", null)
                        .WithMany("CourseGrade")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Models.Student", b =>
                {
                    b.Navigation("CourseGrade");
                });
#pragma warning restore 612, 618
        }
    }
}
